### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [MoeBensu/zsh-some-peco#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by MoeBensu** [comment]
Hi @unixorn,

Thank you for pointing that out! It's weird, as I remember including it. 
Anyway, [it's added now](https://github.com/MoeBensu/zsh-some-peco/blob/master/LICENSE) (again)!
